- name: Configure interfaces file
  template: src=interfaces dest=/etc/network/interfaces
  notify: restart networking

- name: Configure interface ens160
  template: src=interface.ens160 dest=/etc/network/interfaces.d/interface.ens160
  notify: restart networking

- name: Configure interface ens192
  template: src=interface.ens192 dest=/etc/network/interfaces.d/interface.ens192
  notify: restart networking

- name: Enable ip forwarding
  sysctl: name="net.ipv4.ip_forward" value=1 sysctl_set=yes state=present reload=yes

- name: Disable IPv6 - yes, punish me for this one
  sysctl: name="net.ipv6.conf.all.disable_ipv6" value=1 sysctl_set=yes state=present reload=yes

- name: place sudoers file
  copy: src=sudoers dest=/etc/sudoers validate='visudo -cf %s'

- name: install dnsmasq
  apt: name=dnsmasq state=latest cache_valid_time=3600 update_cache=yes

- name: create dnsmasq tftp directory
  file: path=/var/tftpd state=directory owner=dnsmasq group=netdev
  notify: restart dnsmasq

- name: configure dnsmasq
  template: src=dnsmasq.conf dest=/etc/dnsmasq.conf
  notify: restart dnsmasq

- name: enable and run dnsmasq
  service: name=dnsmasq.service enabled=yes state=started

- name: copy toms key
  template: src=tomkey dest=/var/tftpd/tomkey

- name: install grub-efi
  apt: name=grub-efi-amd64-signed

- name: create dnsmasq grub directory
  file: path=/var/tftpd/grub state=directory owner=dnsmasq group=netdev

- name: copy grub binary
  copy:
    remote_src: yes
    src: /usr/lib/grub/x86_64-efi-signed/grubnetx64.efi.signed
    dest: /var/tftpd/grubnetx64.efi
    owner: dnsmasq
    group: netdev
    mode: "0444"

- name: copy grub.cfg
  template:
    src: grub.cfg
    dest: /var/tftpd/grub/grub.cfg
    owner: dnsmasq
    group: netdev
    mode: 0444

- name: create dnsmasq ubuntu-installer directory
  file: path=/var/tftpd/ubuntu-installer state=directory owner=dnsmasq group=netdev

- name: download ubuntu-installer kernel image
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/linux
    dest: /var/tftpd/ubuntu-installer/linux
    mode: 0444
    owner: dnsmasq
    group: netdev

- name: download ubuntu-installer initrd.gz image
  get_url:
    url: http://archive.ubuntu.com/ubuntu/dists/xenial-updates/main/installer-amd64/current/images/netboot/ubuntu-installer/amd64/initrd.gz
    dest: /var/tftpd/ubuntu-installer/initrd.gz
    mode: 0444
    owner: dnsmasq
    group: netdev

- name: copy preseed
  template:
    src: preseed
    dest: /var/tftpd/preseed
    owner: dnsmasq
    group: netdev

- name: create core directory
  file: path=/var/tftpd/coreos state=directory owner=dnsmasq group=netdev

- name: download coreos kernel image
  get_url:
    url: https://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz
    dest: /var/tftpd/coreos/coreos_production_pxe.vmlinuz
    mode: 0444
    owner: dnsmasq
    group: netdev

- name: download coreos initrd image
  get_url:
    url: https://stable.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz
    dest: /var/tftpd/coreos/coreos_production_pxe_image.cpio.gz
    mode: 0444
    owner: dnsmasq
    group: netdev
