- name: Configure kubernetes controller
  hosts:
    - controller
  become: yes
  roles:
    - kubernetes_controller
  vars:
    kubernetes_token: 123456.280ab28a3733115552372784c77eec6f93a3b457

- name: Configure kubernetes nodes
  hosts:
    - nodes
  become: yes
  roles:
    - kubernetes_node
  vars:
    kubernetes_token: 123456.280ab28a3733115552372784c77eec6f93a3b457
    kubernetes_master: 172.16.50.10
